package com.iovation.launchkey.sdk.domain.service;

import java.util.Objects;

/**
 * Object that represents an authorization request
 */
public class AuthorizationRequest {

    /**
     * Unique identifier for the authorization request generated by the LaunchKey API.
     */
    private final String id;

    /**
     * Push package to be sent to Devices when managing your own Device push notifications.
     */
    private final String pushPackage;

    /**
     *
     * @param id Unique identifier for the authorization request generated by the LaunchKey API.
     * @param pushPackage Push package to be sent to Devices when managing your own Device push notifications.
     */
    public AuthorizationRequest(String id, String pushPackage) {
        this.id = id;
        this.pushPackage = pushPackage;
    }

    /**
     * Unique identifier for the authorization request generated by the LaunchKey API.
     * @return Authorization request ID
     */
    public String getId() {
        return id;
    }

    /**
     * Push package to be sent to Devices when managing your own Device push notifications.
     * @return Push package
     */
    public String getPushPackage() {
        return pushPackage;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AuthorizationRequest that = (AuthorizationRequest) o;
        return Objects.equals(id, that.id) &&
                Objects.equals(pushPackage, that.pushPackage);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, pushPackage);
    }

    @Override
    public String toString() {
        return "AuthorizationRequest{" +
                "id='" + id + '\'' +
                ", pushPackage='" + pushPackage + '\'' +
                '}';
    }
}
