/**
 * Copyright 2016 LaunchKey, Inc. All rights reserved.
 *
 * Licensed under the MIT License.
 * You may not use this file except in compliance with the License.
 * A copy of the License is located in the "LICENSE.txt" file accompanying
 * this file. This file is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.launchkey.sdk.transport.v1.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.text.ParseException;
import java.util.Date;

/**
 * Response data from a "ping" call
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class PingResponse {

    /**
     * When the Ping response was generated by Platform API.
     */
    private final Date apiTime;

    /**
     * RSA Public key string returned by the Ping call.
     */
    private final String publicKey;

    /**
     * Finger print of the public key in the response.
     */
    private String fingerprint;

    /**
     * @return When the Ping response was generated by from Platform API.
     */
    public Date getApiTime() {
        return apiTime;
    }

    /**
     * Get the finger print of the public key in the response. Returned only if a key is returned.
     * @return
     */
    public String getFingerprint() {
        return fingerprint;
    }

    /**
     * @return RSA Public key string returned bye the Ping call.
     */
    public final String getPublicKey() {
        return publicKey;
    }

    /**
     * @param fingerprint Fingerprint of the Public Key
     * @param apiTime Time in which the ping response was generated
     * @param publicKey RSA Public key string returned by the Ping call.
     */
    @JsonCreator
    public PingResponse(
            @JsonProperty("fingerprint") String fingerprint,
            @JsonProperty("api_time") Date apiTime,
            @JsonProperty("key") String publicKey
    ) {
        this.fingerprint = fingerprint;
        this.apiTime = apiTime;
        this.publicKey = publicKey;
    }

    @Override
    public String toString() {
        return "PingResponse{" +
                "fingerprint=" + fingerprint +
                ", apiTime=" + apiTime +
                ", publicKey='" + publicKey + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PingResponse)) return false;

        PingResponse that = (PingResponse) o;

        if (fingerprint != null ? !fingerprint.equals(that.fingerprint) : that.fingerprint != null) return false;
        if (apiTime != null ? !apiTime.equals(that.apiTime) : that.apiTime != null) return false;
        return !(publicKey != null ? !publicKey.equals(that.publicKey) : that.publicKey != null);

    }

    @Override
    public int hashCode() {
        int result = fingerprint != null ? fingerprint.hashCode() : 0;
        result = 31 * result + (apiTime != null ? apiTime.hashCode() : 0);
        result = 31 * result + (publicKey != null ? publicKey.hashCode() : 0);
        return result;
    }
}
